[variables]
NODE_VERSION = "22.17.0"
PNPM_VERSION = "10.13.1"

[providers.node]
version = "22.17.0"

[phases.setup]
cmds = ["npm install -g pnpm@10.13.1"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
# Build command using PNPM
cmds = ["pnpm run build"]

[start]
# Start command using PNPM
cmd = "node build"