providers = ["node"]

[variables]
NODE_VERSION = "22.17.0"

[phases.build]
cmds = [
  "npm install -g corepack",
  "corepack enable",
  "corepack prepare pnpm@10.13.1 --activate"
]

[phases.install]
cmds = ["corepack pnpm install"]
