name: 🧑‍🚀 Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  vitest:
    runs-on: ubuntu-latest
    name: ⚡ Testing with Vitest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm 10
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Run Vitest
        run: pnpm test

  svgs-size:
    runs-on: ubuntu-latest
    name: 📦 SVGs Size
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm 10
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install utility dependencies
        run: pnpm install
        working-directory: ./utils/check-size

      - name: Check svgs size
        run: pnpm start
        working-directory: ./utils/check-size
